### ISSUE TITLE
2.1.0 seems to be broken

### ISSUE THREAD

**Issue by ToasterUwU** [jakebailey/pyright-action#89] opened 2024-02-27 12:38 UTC
I have Dependabot setup for many of my projects, and i have 4 automatic PRs for upgrading to 2.1.0, and for all of them the checks fail (which is just testing out the pyright action)

All 4 projects use pyright action once for Linux and once for Windows as the python platform, so i got the following error in the exact same way a total amount of 8 times.

```
Run jakebailey/pyright-action@v2.1.0
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module './impl/format'
Require stack:
- /home/runner/work/_actions/jakebailey/pyright-action/v2.1.0/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at /home/runner/work/_actions/jakebailey/pyright-action/v2.1.0/dist/index.js:4282:25
    at /home/runner/work/_actions/jakebailey/pyright-action/v2.1.0/dist/index.js:4272:17
    at node_modules/jsonc-parser/lib/umd/main.js (/home/runner/work/_actions/jakebailey/pyright-action/v2.1.0/dist/index.js:4278:7)
    at __require (/home/runner/work/_actions/jakebailey/pyright-action/v2.1.0/dist/index.js:12:50)
    at Object.<anonymous> (/home/runner/work/_actions/jakebailey/pyright-action/v2.1.0/dist/index.js:8109:35)
    at Module._compile (node:internal/modules/cjs/loader:1241:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/jakebailey/pyright-action/v2.1.0/dist/index.js'
  ]
}

Node.js v20.8.1
```

**Comment by jakebailey** [comment] 2024-02-27 15:21
Duplicate of #88.

But, apologies. Will fix

**Closed by jakebailey** 2024-02-27 15:21 UTC
